service: uploadToS3

frameworkVersion: ">=1.1.0"

custom:
  bucket: imageStore
  localstack:
    stages:
      - local
    host: http://localhost
    endpointFile: resources/localstack/localstack_endpoints.json
    lambda:
      mountCode: True
provider:
  name: aws
  runtime: nodejs12.x
  environment:
    NODE_ENV: dev

functions:
  unknownRoute404:
    handler: target/app/handler
    events:
      - http:
          path: /
          method: get

plugins:
  - serverless-plugin-typescript
  - serverless-localstack
  - serverless-offline